# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3fb4f11bb6e42800328fc220461a59c5beb161e285e077673ca93582feffbc9819353b30560e7231944fb64f8a97784778ad0497eb26a66f5064e53ac0d523c

test:
  secret_key_base: 5cbc22d9e669ccd399c10aca9008009fce8fcace810f52214365a87672b78e4d0f6f0c70fd1806592b87c610aa8496448cd6af5a82a594d42d63e10775df0051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 160c6a1baa4196651cc04ec8078c753e4ccc0ae6ba1003e5709401599206e0925786cd7b8b5dbaebfedcae8c0ee46a06f3a799945fed46e5901e7c2aed8e88d1
  
